version: '3.9'
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - postgres
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - safe

  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - safe

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ToyotaProject
    networks:
      - safe

  sales-service:
    build:
      context: ./sales-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ToyotaProject
    networks:
      - safe

  report-service:
    build:
      context: ./report-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ToyotaProject
    networks:
      - safe

  usermanagement-service:
    build:
      context: ./usermanagement-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ToyotaProject
    networks:
      - safe

  authenticationauthorization-service:
    build:
      context: ./authenticationauthorization-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ToyotaProject
    networks:
      - safe

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ToyotaProject
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - safe

volumes:
  postgres_data:

networks:
  safe: