eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: sales-getSales
          uri: lb://sales-service
          predicates:
            - Path=/api/sales/get-all
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "MANAGER"
        - id: sales
          uri: lb://sales-service
          predicates:
            - Path=/api/sales/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "CASHIER"
        - id: sales-campaign
          uri: lb://sales-service
          predicates:
            - Path=/api/campaigns/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "CASHIER"
        - id: report
          uri: lb://report-service
          predicates:
            - Path=/api/reports/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "MANAGER"
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: ""
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product-categories/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: ""
        - id: authentication-authorization-service
          uri: lb://authentication-authorization-service
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "ADMIN"
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/api/user-management/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "ADMIN"